### PR TITLE
fix: weavelet cpu consumption

### LINKED ISSUE #92: CPU consumption at 100% running hello example
After to run the `hello` example with `go run .` the CPU consumption was at 100%

pprof output
```
(pprof) top
Showing nodes accounting for 29.98s, 100% of 29.99s total
Dropped 7 nodes (cum <= 0.15s)
      flat  flat%   sum%        cum   cum%
    15.66s 52.22% 52.22%     29.98s   100%  github.com/ServiceWeaver/weaver.(*weavelet).watchComponentsToStart
     9.71s 32.38% 84.59%     11.14s 37.15%  github.com/ServiceWeaver/weaver/runtime/retry.(*Retry).Continue
     3.18s 10.60% 95.20%      3.18s 10.60%  github.com/ServiceWeaver/weaver.(*singleprocessEnv).GetComponentsToStart
     1.43s  4.77%   100%      1.43s  4.77%  context.(*emptyCtx).Err
         0     0%   100%     29.98s   100%  github.com/ServiceWeaver/weaver.startWork.func1
```

### PR DESCRIPTION
**Pull request by mishudark**
After to run the hello example with `go run .` the cpu consumption was at 100%, this change adds a blocking feature to `getcomponentstostart` in `singleprocess.go`, this prevents the excessive CPU consumption

Before:
```
(pprof) top
Showing nodes accounting for 29.98s, 100% of 29.99s total
Dropped 7 nodes (cum <= 0.15s)
      flat  flat%   sum%        cum   cum%
    15.66s 52.22% 52.22%     29.98s   100%  github.com/ServiceWeaver/weaver.(*weavelet).watchComponentsToStart
     9.71s 32.38% 84.59%     11.14s 37.15%  github.com/ServiceWeaver/weaver/runtime/retry.(*Retry).Continue
     3.18s 10.60% 95.20%      3.18s 10.60%  github.com/ServiceWeaver/weaver.(*singleprocessEnv).GetComponentsToStart
     1.43s  4.77%   100%      1.43s  4.77%  context.(*emptyCtx).Err
         0     0%   100%     29.98s   100%  github.com/ServiceWeaver/weaver.startWork.func1
```

After:
```
(pprof) top
Showing nodes accounting for 90ms, 100% of 90ms total
Showing top 10 nodes out of 27
      flat  flat%   sum%        cum   cum%
      30ms 33.33% 33.33%       30ms 33.33%  runtime/internal/syscall.Syscall6
      10ms 11.11% 44.44%       10ms 11.11%  runtime.(*limiterEvent).stop
      10ms 11.11% 55.56%       50ms 55.56%  runtime.findRunnable
      10ms 11.11% 66.67%       10ms 11.11%  runtime.futex
      10ms 11.11% 77.78%       10ms 11.11%  runtime.nextFreeFast (inline)
      10ms 11.11% 88.89%       10ms 11.11%  runtime.runqget
      10ms 11.11%   100%       10ms 11.11%  time.startTimer
         0     0%   100%       20ms 22.22%  github.com/ServiceWeaver/weaver.(*weavelet).watchComponentsToStart
         0     0%   100%       20ms 22.22%  github.com/ServiceWeaver/weaver.startWork.func1
         0     0%   100%       10ms 11.11%  runtime.futexwakeup
```

fixes #92

### CODE REVIEW

**Comment by mishudark** [comment]
sure thing, thanks for the guidance, I have updated the PR :)

File: singleprocess.go [hunk 1]
```diff
@@ -161,6 +161,8 @@ func (e *singleprocessEnv) RegisterComponentToStart(_ context.Context, _ string,
 }
 
 func (e *singleprocessEnv) GetComponentsToStart(context.Context, *call.Version) ([]string, *call.Version, error) {
+	// blocks forever to avoid excessive CPU consumption in weavelet.watchComponentsToStart
```
Comment (spetrovic77) [inline singleprocess.go:164]: Thanks, this is even more concise.

Could you just change the comment to:

`// Block forever since there's not going to be anything to start.`

File: singleprocess.go [hunk 2]
```diff
@@ -161,6 +161,8 @@ func (e *singleprocessEnv) RegisterComponentToStart(_ context.Context, _ string,
...
+	<-make(chan struct{})
```
Comment (dnephin) [inline singleprocess.go:165]: Would it make sense to block on `ctx.Done()` so that this operation can shut down gracefully when the context is cancelled?

```suggestion
func (e *singleprocessEnv) GetComponentsToStart(ctx context.Context, _*call.Version) ([]string, *call.Version, error) {
	// Block forever since there's not going to be anything to start.
	<-ctx.Done()
```

Comment (spetrovic77) [reply singleprocess.go:165]: Ah yes, this is indeed better.

**Review by spetrovic77 — APPROVED** [review]

File: singleprocess.go [hunk 3]
```diff
@@ -160,7 +160,9 @@ func (e *singleprocessEnv) RegisterComponentToStart(_ context.Context, _ string,
 	return nil
 }
 
-func (e *singleprocessEnv) GetComponentsToStart(context.Context, *call.Version) ([]string, *call.Version, error) {
+func (e *singleprocessEnv) GetComponentsToStart(ctx context.Context, _*call.Version) ([]string, *call.Version, error) {
```
Comment (dnephin) [inline singleprocess.go:163]: Oops, I missed a space in my suggested edit
```suggestion
func (e *singleprocessEnv) GetComponentsToStart(ctx context.Context, _ *call.Version) ([]string, *call.Version, error) {
```

**Comment by spetrovic77** [comment]
We're trying to figure out why workflows aren't running in the forked repos.

**Comment by dnephin** [comment]
> We're trying to figure out why workflows aren't running in the forked repos.

I'm guessing it's this:

https://github.com/ServiceWeaver/weaver/blob/f7c2dd71b946d309d959363a85d59bbf96bc984f/.github/workflows/go.yml#L17

This needs `pull_request` added to the list of `on:` targets.

Once that's done the prompt to approve should show up:
https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

I can PR that change

**Comment by spetrovic77** [comment]
Awesome, let me try that!
